### ISSUE TITLE
WeakMap?

### ISSUE THREAD

**Issue by ajmas** [PieterT2000/stopwatch.js#1]
Is there any reason you are using `WeakMap` in your code?

**Comment by PieterT2000** [comment]
@ajmas 👍 for showing interest in [stopwatch.js](https://github.com/PieterT2000/stopwatch.js)!

I've used `WeakMap` with the intent of having private properties, but you could obviously achieve the same with other solutions like using regular variables outside the exported scope. 
Another reason I've used `WeakMap` was that I was pretty new to the concept and just wanted to try it out for fun. 😄 

Hope this clears things up, and if you've got any other questions I would be happy to help!
